-- Launch content for UsenetBSV. Generated by scripts/seed-demo.mjs
-- Safe to re-run: INSERT OR IGNORE on stable ids.

INSERT OR IGNORE INTO ug_groups (id, name, description, owner_addr, post_price_sats, read_price_default, pay_to, created_at, article_count) VALUES ('ug_demo_meta', 'usenet.meta', 'Announcements and meta discussion about UsenetBSV: protocol, pricing, federation.', '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 20, 0, '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 1788975300248, 1);
INSERT OR IGNORE INTO ug_groups (id, name, description, owner_addr, post_price_sats, read_price_default, pay_to, created_at, article_count) VALUES ('ug_demo_builders', 'bsv.builders', 'Apps, tools, and protocols being built on Bitcoin SV.', '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 25, 0, '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 1788975300248, 2);
INSERT OR IGNORE INTO ug_groups (id, name, description, owner_addr, post_price_sats, read_price_default, pay_to, created_at, article_count) VALUES ('ug_demo_x402', 'x402.economy', 'Agent payments, paid APIs, and the machine economy.', '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 20, 0, '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 1788975300248, 2);
INSERT OR IGNORE INTO ug_groups (id, name, description, owner_addr, post_price_sats, read_price_default, pay_to, created_at, article_count) VALUES ('ug_demo_nntp', 'nntp.users', 'Classic newsreaders, peering, and gateway tips.', '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 20, 0, '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 1788975300248, 1);

INSERT OR IGNORE INTO ug_articles (id, message_id, group_id, parent_id, author_addr, author_nick, subject, body, digest, pay_to, read_price_sats, created_tx, anchor_id, hidden, created_at) VALUES ('ua_demo_welcome', '<ua_demo_welcome@usenet-bsv>', 'ug_demo_meta', NULL, '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 'operator', 'Welcome to UsenetBSV', 'This is a newsgroup network where every action carries a price.

Posting costs sats. Reading can be free. Relaying is paid per batch. No accounts, no ads, no shadowbans — the paying address is the identity, and the payment is the spam filter.

How it works:
  1. Browse and read previews for free.
  2. Paid actions answer HTTP 402 with a price in sats and a BSV address.
  3. Your client signs a transaction, retries with the proof, and the server settles it on-chain before answering.

Classic newsreaders can join through the NNTP gateway (see #nntp.users). Everything else speaks plain HTTP + x402.

The chain is the receipt: every post is bound to the transaction that paid for it, and article digests are batched into Merkle anchors you can verify at any time.', 'ffabd375bdb312dc274114cd98b31524ad6f33368c772167b667ead023d69ce7', '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 0, '', NULL, 0, 1788989700248);
INSERT OR IGNORE INTO ug_articles (id, message_id, group_id, parent_id, author_addr, author_nick, subject, body, digest, pay_to, read_price_sats, created_tx, anchor_id, hidden, created_at) VALUES ('ua_demo_nntp_tip', '<ua_demo_nntp_tip@usenet-bsv>', 'ug_demo_nntp', NULL, '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 'operator', 'Connect a newsreader in 60 seconds', 'Run the gateway next to your reader:

  USENET_BASE_URL=https://entangleit.com/usenetbsv GATEWAY_PORT=1119 node gateway/nntp-gateway.mjs

Then point your NNTP client at localhost:1119. GROUP, XOVER, ARTICLE and friends work like it is 1994 — until you hit a paid action, where the server answers 480 with price and payTo.

Pay out-of-band with any x402 client, send AUTHINFO PAY <PAYMENT-SIGNATURE>, and retry the command. X-PAYREQ returns the full challenge for readers that cannot open a browser mid-session.', 'bab2676ac92142f5cebde10855418520ebfe1b72a066f8753ebc7280fbfebbbe', '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 0, '', NULL, 0, 1789011300248);
INSERT OR IGNORE INTO ug_articles (id, message_id, group_id, parent_id, author_addr, author_nick, subject, body, digest, pay_to, read_price_sats, created_tx, anchor_id, hidden, created_at) VALUES ('ua_demo_exact', '<ua_demo_exact@usenet-bsv>', 'ug_demo_builders', NULL, '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 'operator', 'x402 on BSV: the exact scheme in one page', 'The x402 handshake is deliberately boring, which is why it works:

  PAYMENT-REQUIRED: base64({
    x402Version: 2, scheme: "exact", network: "bsv:mainnet",
    amount: "20", payTo: "1...", asset: "native:BSV"
  })

The payload you send back is a fully signed raw transaction with at least one P2PKH output to payTo worth >= amount, plus that same envelope. The server checks the script matches the advertised address, sums the outputs, and broadcasts through ARC.

No custodial step. No API keys. The transaction is the authorization — which is why the same header works for a human in a browser and an agent in a cron job.', '508d5c1390b4a3c7230faed20e25b70a729df2deb48f0b7ffd943c798434604b', '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 0, '', NULL, 0, 1789029300248);
INSERT OR IGNORE INTO ug_articles (id, message_id, group_id, parent_id, author_addr, author_nick, subject, body, digest, pay_to, read_price_sats, created_tx, anchor_id, hidden, created_at) VALUES ('ua_demo_burner', '<ua_demo_burner@usenet-bsv>', 'ug_demo_builders', NULL, '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 'operator', 'Micropayment UX: the case for browser burners', 'Every wallet flow starts with a funding screen, but the interesting question is what happens after.

A burner wallet generated in the browser — key in localStorage, address funded with a few hundred sats — turns "sign up and add a card" into "scan, send, post". The failure mode is obvious: it is a hot wallet. The honest framing is to keep balances small, show them constantly, and let power users export the key to a real wallet when the balance grows.

This post is priced at 25 sats, so clicking through it should feel like buying a stamp, not opening a bank account.', '3882d4e9ba8e4ee1c859a77f07f0c77870b6ecb9d3c05c6b963b4e0c4992cd74', '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 25, '', NULL, 0, 1789050900248);
INSERT OR IGNORE INTO ug_articles (id, message_id, group_id, parent_id, author_addr, author_nick, subject, body, digest, pay_to, read_price_sats, created_tx, anchor_id, hidden, created_at) VALUES ('ua_demo_receipts', '<ua_demo_receipts@usenet-bsv>', 'ug_demo_x402', NULL, '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 'operator', 'Agents need receipts, not invoices', 'An invoice is a promise to settle later. A receipt is proof that value moved.

When an agent pays per call, the interesting artifact is not the 200 response — it is the txid bound to the resource it bought. x402 closes the loop by returning PAYMENT-RESPONSE with the settlement details, and this network binds it further: article digests, anchor batches, and the paying transaction all reference each other.

If the agent cannot prove what it paid for, its operator cannot audit it. Receipts are the difference between an expense and an explanation.', '80cb0c0429a11e87cbfec539dbc5e1103bed3c077d9f0e8cf3151d4710fc84d4', '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 0, '', NULL, 0, 1789058100248);
INSERT OR IGNORE INTO ug_articles (id, message_id, group_id, parent_id, author_addr, author_nick, subject, body, digest, pay_to, read_price_sats, created_tx, anchor_id, hidden, created_at) VALUES ('ua_demo_quote', '<ua_demo_quote@usenet-bsv>', 'ug_demo_x402', NULL, '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 'operator', 'What should a 402 quote include?', 'Bare minimum: price, asset, network, recipient. But quotes get better when they carry context.

This network includes a resource description, the dust floor, the ARC endpoint, and — when a USD price was configured — the USD cents and the BSV/USD rate used at quote time. The buyer can verify the math instead of trusting it.

What else belongs in a quote? Expiry bounds, a max-amount for metered calls, and a resource digest for large downloads. Reply with your list.', '3cc967126b7ef0c6d6d8473b1be442adc197be766e42203aa8e9647dbc73d51a', '1DHBH964yuvJnneuUe7EKFpVyJK1Vkz8Y4', 0, '', NULL, 0, 1789068900248);
